'use strict'

export const SET_SELECTED_ITEM             = 'SET_SELECTED_ITEM';
export const CLEAR_SELECTED_ITEM           = 'CLEAR_SELECTED_ITEM';
export const SET_REQUEST_BINDING_DATA      = 'SET_REQUEST_BINDING_DATA';
export const SET_SERVER_BINDING_DATA       = 'SET_SERVER_BINDING_DATA';
export const SET_APPLICATION_BINDING_DATA  = 'SET_APPLICATION_BINDING_DATA';
